In [5]:
import numpy as np
import scipy
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from itertools import product
import os
from utils import get_sample_freq, get_test_freq, get_stimulus, remove_outliers

mode = 'Frequency'
starting_point = 1.0
window_size = 2.5

sample_path = f'./sample_{mode}/data_sp{starting_point}ws{window_size}/sample_spike_neuron'
test_path = f'./test_{mode}/data_sp{starting_point}ws{window_size}/test_spike_case'

#starting_point_types = [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.]
#window_size_types = [1,1.5,2,2.5,3,3.5,4]

stimulus_raw = scipy.io.loadmat('dat_stimulus.mat')
spk_sample_raw = scipy.io.loadmat('dat_spk_sample.mat')
spk_test_raw = scipy.io.loadmat('dat_spk_test.mat')

stimulus = stimulus_raw['stimulus']
spk_sample = spk_sample_raw['spk_sample']
spk_test = spk_test_raw['spk_test']

degrees = np.unique(stimulus[:,1])
print(degrees)

[  0.  20.  40.  60.  80. 100. 120. 140. 160.]


In [6]:
def get_data(i, type = 'Neuron'):
    if type.lower() == 'neuron':
        return pd.read_csv(sample_path + f'{i}.csv')
    elif type.lower() == 'case':
        return pd.read_csv(test_path + f'{i}.csv')

In [12]:
##make_binomial
def get_likelihood(df, percentile_threshold = 50):
    result = {}
    thr = np.percentile(df[mode].values, q = percentile_threshold)
    for degree in degrees:
        l = (df[df['Degree'] == int(degree)][mode].values > thr)*1
        result[int(degree)] = l
    return result

Neurons = {}
for n in np.arange(1,11):
    df = get_data(n, type = 'Neuron')
    Neurons[n] = get_likelihood(df)

Cases = {}
for n in np.arange(1,11):
    df = get_data(n, type = 'Case')
    Cases[n] = get_likelihood(df)

In [39]:
## Frequentist approach

#Binomial distribution: 
    # X ~ Bin(n, p), then E(X) = np, Var(X) = np(1-p)
from math import sqrt
def get_MLE(data_dict):
    Mean = []
    Std = []

    for i in data_dict:
        l = data_dict[i]
        l_mean = []
        l_std = []
        for degree in degrees:
            n = len(l[degree])
            s = sum(l[degree])
            f = n - s

            p = s / n 

            mu_hat = n * p
            sig_hat = sqrt(n * p * (1-p))

            l_mean.append(mu_hat)
            l_std.append(sig_hat)

        Mean.append(l_mean)
        Std.append(l_std)

    return np.array(Mean), np.array(Std)


In [43]:
Freq_Neuron_mean, Freq_Neuron_std = get_MLE(Neurons)
Freq_Case_mean, Freq_Case_std = get_MLE(Cases)

Bayes rule: posterior = likelihood * prior / evidence
evidence 는 구하기 힘듦으로 보통 posterior 가 likelihood * prior에 비례한다고 많이 함.

Beta Distribution & Binomial-Beta conjugacy 

Conjugacy prior: 

In [21]:
## Bayesian Approach 
from math import sqrt

#Set prior parameters
a0 = 2.
b0 = 2.

def get_posterior(data_dict, a0 = 2., b0 = 2.):
    Mean = []
    Std = []

    for i in data_dict:
        l = data_dict[i]
        l_mean = []
        l_std = []
        for degree in degrees:
            n = len(l[degree])
            s = sum(l[degree])
            f = n - s

            a_post = a0 + s
            b_post = b0 + f

            #Compute mean & std of the posterior distribution
            mu_post = a_post / (a_post + b_post)
            sig_post = sqrt((a_post*b_post)/(((a_post + b_post)**2)*(a_post + b_post + 1)))

            l_mean.append(mu_post)
            l_std.append(sig_post)
        Mean.append(l_mean)
        Std.append(l_std)

    return np.array(Mean), np.array(Std)

In [22]:
Bayes_Neuron_mean, Bayes_Neuron_std = get_posterior(Neurons)
Bayes_Case_mean, Bayes_Case_std = get_posterior(Cases)

In [41]:
from itertools import permutations
from tqdm import tqdm


def estimate_permutation(Case_mean, Neuron_mean):
    min_ls_error = np.inf
    P_ls_2 = None

    for perm in tqdm(permutations(range(10))):
        P = np.eye(10)[list(perm)]
        ls_error = np.linalg.norm(Case_mean - P @ Neuron_mean)
        if ls_error < min_ls_error:
            min_ls_error = ls_error
            P_ls_2 = P
        
    print('Least Square Perm Matrix')
    print(P_ls_2)

    return P_ls_2, min_ls_error


In [42]:
P, error = estimate_permutation(Case_mean=Freq_Case_mean, Neuron_mean=Freq_Neuron_mean)

3628800it [01:29, 40488.33it/s]

Least Square Perm Matrix
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
P, error = estimate_permutation(Case_mean=Bayes_Case_mean, Neuron_mean=Bayes_Neuron_mean)